source "http://rubygems.org"
ruby "2.3.1"

gem "bundler"
gem "cocoapods", "~> 1.0.0"
gem "danger", "~> 0.10.0"
gem "jazzy", git: "https://github.com/realm/jazzy.git", ref: "8b88e33"
gem "scan"
gem "slather"
gem "xcpretty"
