default_platform(:ios)

config = {
  workspace: "QuickTableViewController.xcworkspace",
  clean: true,
  skip_build: true,
  code_coverage: true
}

desc "Test Swift Package"
lane :swift_package do
  Dir.chdir("../Package") do
    sh [
      %(set -o pipefail &&),
      %(xcodebuild -project Package.xcodeproj -scheme Package -sdk iphonesimulator clean build),
      %(| bundle exec xcpretty -c)
    ].join " "
  end
end

platform :ios do
  desc "Run iOS unit tests"
  lane :unit_tests do
    run_tests(config.merge(scheme: "QuickTableViewController-iOS"))
  end

  desc "Run iOS UI tests"
  lane :ui_tests do
    run_tests(config.merge(scheme: "Example-iOS"))
  end
end

platform :tvos do
  desc "Run tvOS unit tests"
  lane :unit_tests do
    run_tests(config.merge(scheme: "QuickTableViewController-tvOS"))
  end

  desc "Run tvOS UI tests"
  lane :ui_tests do
    run_tests(config.merge(scheme: "Example-tvOS"))
  end
end
